Deployment improvements
aateem/netchecker-server pull request #1
Opened 2016-09-30 14:55 UTC by bogdando

Make sure to rebuild the netcheck server container before to merge/test

2016-09-30 14:57 UTC, bogdando commented
@adidenko

2016-11-02 10:46 UTC, bogdando commented
@aateem @adidenko

2016-11-04 14:57 UTC, aateem requested changes
I agree with the changes to utility scripts, but please clarify your intentions for logging part: what do you want to achieve? Thus I recommend you to split up the PR, so that we could separately discuss the logging.

2016-11-04 14:57 UTC, aateem commented on netchecker_server/application.py
> +logging.basicConfig()
Please, refer to the documentation for basicConfig https://docs.python.org/2/library/logging.html#logging.basicConfig 
As long as you set up separate stream handler 'ch' you will have logging entries doubled in the display.

2016-11-04 14:57 UTC, aateem commented on netchecker_server/application.py
> +root.propagate = True
Root logger is the 'highest' ancestor logger so don't need to set 'propagate' for it.

2016-11-04 14:57 UTC, aateem commented on netchecker_server/application.py
> +requests_log = logging.getLogger("requests.packages.urllib3")
I believe you were driven by this bit of requests documentation http://docs.python-requests.org/en/master/api/?highlight=logging#migrating-to-1-x particularly section about logging, weren't you? Now in case if I use requests directly in the code I would see a tonne of not very useful information (for me, at least) about the request I made. Why do you want to display such information?

2016-11-04 14:57 UTC, aateem commented on netchecker_server/application.py
> +logging.basicConfig()
Also I would like to put root logging configuration into separate module and call the set up at entry point level of the application, i.e. in server.py.

2016-11-04 15:19 UTC, bogdando commented
@aateem done

2016-11-07 12:04 UTC, aateem requested changes
Additional fixes needed

2016-11-07 12:04 UTC, aateem commented on netchecker_server/application.py
> -K8S_API_URL = 'http://localhost:8001/api/v1/'
I suppose you've deleted this accidentally. Pls, fix.

2016-11-07 12:04 UTC, aateem commented on netchecker_server/application.py
> +    # Raises SystemExit(0):
Obvious comment

2016-11-07 12:04 UTC, aateem commented on netchecker_server/application.py
> +def sigterm_handler(_signo, _stack_frame):
Let's move this on server start level, i.e. to server.py

2016-11-07 13:46 UTC, bogdando commented
@aateem done!

2016-11-08 15:16 UTC, aateem requested changes
I would like to use the deployment script separately from Kargo, thus please, rework your PR to retain that possibility.

2016-11-08 15:16 UTC, aateem commented on utils/deploy_netchecker.sh
> +cat << EOF > {{ kube_config_dir }}/netchecker-server-pod.yml
Maybe store location for k8s ymls in some variable w/ default value but which also can be populated by an environment variable if present?

2016-11-08 15:16 UTC, aateem commented on utils/deploy_netchecker.sh
> +cat << EOF > {{ kube_config_dir }}/netchecker-server-svc.yml
ditto

2016-11-08 15:16 UTC, aateem commented on utils/deploy_netchecker.sh
> +cat << EOF > {{ kube_config_dir }}/netchecker-agent-ds.yml
ditto

2016-11-08 15:16 UTC, aateem commented on utils/deploy_netchecker.sh
> +cat << EOF > {{ kube_config_dir }}/netchecker-agent-hostnet-ds.yml
ditto

2016-11-08 15:43 UTC, bogdando commented on utils/deploy_netchecker.sh
> +cat << EOF > {{ kube_config_dir }}/netchecker-server-pod.yml
oops, I forgot to remove these jinja2 vars while copy pasted from ansible templates...

2016-11-08 16:36 UTC, bogdando commented
here it is. works for me

2016-11-08 17:07 UTC, merged